### ISSUE TITLE
mesh and texture files of some models is not used

### ISSUE THREAD

**Issue by Jialn** [HorizonRobotics/SocialRobot#102]
https://github.com/HorizonRobotics/SocialRobot/pull/97
PR97 added all used gazebo model files into repository, but mesh and texture files of the model that are renamed is not used. The link in the sdf is still the original one. Currently we still need to downloading model files to ~/.gazebo/models to get the texture correctly.

example: here is part of the codes pr2_noplugin.sdf

```
      <collision name="torso_lift_link_geom">
        <geometry>
          <mesh>
            <uri>model://pr2/meshes/torso_v0/torso_lift_L.stl</uri>
          </mesh>
        </geometry>
```
Either we should change pr2 in the uri to pr2_noplugin, or remove the mesh and texture file and add originlal pr2/pioneer/youbot to the repo.

**Comment by le-horizon** [comment]
Good catch Jiangtao!  I guess changing URI to pr2_noplugin is the easiest?  Thanks!

**Comment by Jialn** [comment]
Fxied
