### ISSUE TITLE
cannot run the test_env

### ISSUE THREAD

**Issue by ChenyangRan** [HorizonRobotics/SocialRobot#129]
Hi, I have installed the gazebo 9.13.2 and pip install the pkg.
However, I cannot run the env correctly.
The error is 
```
SocialRobot/python/social_bot/__init__.py", line 66, in <module>
    from . import pygazebo
ImportError: /usr/local/lib/libopencv_imgproc.so.2.4: undefined symbol: _ZNK2cv9Algorithm5writeERNS_11FileStorageE

```
I'm sure I have written the path as the guidance, my python version is 3.7.
Is there anyone help me?

**Comment by hnyu** [comment]
It seems that while building pygazebo.*.so, the opencv library is not correct. Make sure to check the output message of cmake and make?

**Comment by ChenyangRan** [comment]
> It seems that while building pygazebo.*.so, the opencv library is not correct. Make sure to check the output message of cmake and make?

It can work now. I have installed the pkg on another computer.
