### ISSUE TITLE
Can't set a seed to fix return.

### ISSUE THREAD

**Issue by www2171668** [HorizonRobotics/SocialRobot#139]
Hello. I see some changes such as "Implement gym.Env.seed()". But I still can't get a fix return. My origin code is ALF. When I use Fetch or Ant env, the seed works. So I don't know how to fix SocialRobot seed to get a gix return.

**Comment by le-horizon** [comment]
Thanks for the ping.

It seems you are on the right track.
This PR https://github.com/HorizonRobotics/SocialRobot/pull/133, and this commit in particular:
https://github.com/HorizonRobotics/SocialRobot/pull/133/commits/8bd875373b43dd02d30208176fa097b05bde2ee3
will likely fix the problem (need re-compiling).

The comment about "implement gym.Env.seed()" is just a better way to solve it.  We'll look into it, too busy at the moment.

**Comment by www2171668** [comment]
Thank you for replying. I will try it.
