### ISSUE TITLE
The test environment for this repo?

### ISSUE THREAD

**Issue by 20chase** [HorizonRobotics/SocialRobot#16]
Hi developers,

Thanks for your amazing job. But I can not compile this repo for my Gazebo 8 (built from source), so I am wondering which version of the Gazebo is tested in your environment. In other words, can you list the details of your developing environment (e.g. the version of the system, is it required ROS)

Thanks in advance. Looking forward to your reply.

**Comment by emailweixu** [comment]
The project is built using Gazebo 9. It does not need ROS.

**Comment by 20chase** [comment]
Thanks for your reply. Posting this information in README will be appreciated : )

**Comment by emailweixu** [comment]
Yes, it's updated. Can you compile with newer version of Gazebo?

**Comment by 20chase** [comment]
Yes, I compiled it with Gazebo 9.8.0.
