### ISSUE TITLE
Compiling error in pygazebo.cc

### ISSUE THREAD

**Issue by WinnieLaugh** [HorizonRobotics/SocialRobot#17]
Hi developers,

Thank you very much for your wonderful work!

I ran into an error when trying to compile the project by 'make -j'.  And the error goes like this:

/home/workspace/SocialRobot/SocialRobot/pygazebo/pygazebo.cc: In member function ‘bool social_bot::Agent::TakeAction(const std::map<std::__cxx11::basic_string<char>, double>&)’:
/home/workspace/SocialRobot/SocialRobot/pygazebo/pygazebo.cc:230:30: error: ‘class gazebo::physics::JointController’ has no member named ‘SetForce’; did you mean ‘GetForces’?
       bool ret = controller->SetForce(name2force.first, name2force.second);

May I ask for your help to check with this? I am trying to compile it on Ubuntu 18.04 with gazebo 9.0. 

Thanks in advance.

**Comment by emailweixu** [comment]
SetForce() was introduced in Gazebo 9.5.0.  You need to upgrade to a later version of Gazebo.

**Comment by WinnieLaugh** [comment]
Got it. Thanks a lot for your quick reply!
