### ISSUE TITLE
Unable to find sensor: camera, Segmentation fault: 11

### ISSUE THREAD

**Issue by ruizhaogit** [HorizonRobotics/SocialRobot#20]
Hi guys,

Does anyone know how solve the following error (and Python quit unexpectedly.):

"$ python3.7 examples/test_simple_navigation.py
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.181.55.63
[Err] [LogRecord.cc:157] LogRecord has not been initialized.
 joint name: pioneer2dx::pioneer2dx::left_wheel_hinge
 joint name: pioneer2dx::pioneer2dx::right_wheel_hinge
 joint name: pioneer2dx::camera_joint
INFO:social_bot.envs.simple_navigation:joint names: ['pioneer2dx::pioneer2dx::left_wheel_hinge', 'pioneer2dx::pioneer2dx::right_wheel_hinge', 'pioneer2dx::camera_joint']
 joint name: pioneer2dx::pioneer2dx::left_wheel_hinge
 joint name: pioneer2dx::pioneer2dx::right_wheel_hinge
 joint name: pioneer2dx::camera_joint
unable to find sensor: camera
Segmentation fault: 11"

Thanks!
-Rui

**Comment by ruizhaogit** [comment]
segmentation fault occurs on line "env = gym.make("SocialBot-SimpleNavigation-v0")"

**Comment by ruizhaogit** [comment]
test environment: OS X

**Comment by bayesian** [comment]
can you add line:
"self._world.info()" in SimpleNavigation class __init__ method, before call self._agent.get_camera_observation? 

it will print out all sensors and the scope name.

**Comment by ruizhaogit** [comment]
OK, I add self._world.info(), it outputs:
"[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.178.20
[Err] [LogRecord.cc:157] LogRecord has not been initialized.
 joint name: pioneer2dx::pioneer2dx::left_wheel_hinge
 joint name: pioneer2dx::pioneer2dx::right_wheel_hinge
 joint name: pioneer2dx::camera_joint
INFO:social_bot.envs.simple_navigation:joint names: ['pioneer2dx::pioneer2dx::left_wheel_hinge', 'pioneer2dx::pioneer2dx::right_wheel_hinge', 'pioneer2dx::camera_joint']
 joint name: pioneer2dx::pioneer2dx::left_wheel_hinge
 joint name: pioneer2dx::pioneer2dx::right_wheel_hinge
 joint name: pioneer2dx::camera_joint
 ==== world info ====
 world state: <state world_name='default'><sim_time>0 0</sim_time><wall_time>1556916339 622487161</wall_time><real_time>1556916339 622476896</real_time><iterations>0</iterations><model name='east_wall'><pose>0 1.5 0.1 0 -0 0 </pose><link name='link'><pose>0 1.5 0.1 0 -0 0 </pose></link></model><model name='goal'><pose>1 1 0 0 -0 0 </pose><link name='link'><pose>1 1 0 0 -0 0 </pose></link></model><model name='ground_plane'><pose>0 0 0 0 -0 0 </pose><link name='link'><pose>0 0 0 0 -0 0 </pose></link></model><model name='north_wall'><pose>-1.5 0 0.1 0 -0 0 </pose><link name='link'><pose>-1.5 0 0.1 0 -0 0 </pose></link></model><model name='pioneer2dx'><pose>0 0 0 0 -0 0 </pose><link name='pioneer2dx::chassis'><pose>0 0 0.16 0 -0 0 </pose></link><link name='pioneer2dx::left_wheel'><pose>0.1 0.17 0.11 -0 1.571 1.571 </pose></link><link name='pioneer2dx::right_wheel'><pose>0.1 -0.17 0.11 -0 1.571 1.571 </pose></link><model name='camera'><pose>0.2 0 0.35 0 -0 0 </pose><link name='link'><pose>0.2 0 0.35 0 -0 0 </pose></link></model></model><model name='south_wall'><pose>1.5 0 0.1 0 -0 0 </pose><link name='link'><pose>1.5 0 0.1 0 -0 0 </pose></link></model><model name='west_wall'><pose>0 -1.5 0.1 0 -0 0 </pose><link name='link'><pose>0 -1.5 0.1 0 -0 0 </pose></link></model><light name='sun'><pose>0.000 0.000 10.000 0.000 -0.000 0.000 </pose></light></state>
Model: ground_plane
Link: ground_plane::link
Model: pioneer2dx
Link: pioneer2dx::pioneer2dx::chassis
Link: pioneer2dx::pioneer2dx::right_wheel
Link: pioneer2dx::pioneer2dx::left_wheel
Joint: pioneer2dx::pioneer2dx::left_wheel_hinge
DOF: 1
Position 0:0.000
Velocity 0:0.000
Joint: pioneer2dx::pioneer2dx::right_wheel_hinge
DOF: 1
Position 0:0.000
Velocity 0:0.000
Joint: pioneer2dx::camera_joint
DOF: 1
Position 0:0.000
Velocity 0:0.000
Model: goal
Link: goal::link
Model: south_wall
Link: south_wall::link
Model: north_wall
Link: north_wall::link
Model: east_wall
Link: east_wall::link
Model: west_wall
Link: west_wall::link
 === the end of world ===
unable to find sensor: camera
Segmentation fault: 11"

**Comment by ruizhaogit** [comment]
Yes, the gazebo version is 9.8.0

**Comment by ruizhaogit** [comment]
The problem is the "Segmentation fault: 11" caused by the line "gazebo.initialize(port=port)" in the "simple_navigation.py" script.

**Comment by bayesian** [comment]
can you run something like:

GAZEBO_MODEL_PATH=/home/taoxu/src/SocialRobot/python/social_bot/models/ gazebo ~/src/SocialRobot/python/social_bot/worlds/pioneer2dx_camera.world

just to see if the world looks good in gazebo, do you see the white camera box on top of the cart?
from your info section, it seems the camera is in the world.

**Comment by ruizhaogit** [comment]
The world seems look good in gazebo.
Yes, I see the white camera box on top of the cart.
<img width="961" alt="Screenshot 2019-05-03 at 23 02 04" src="https://user-images.githubusercontent.com/18663623/57165548-b9056900-6df7-11e9-90a0-89d650cec876.png">

**Comment by bayesian** [comment]
you should see
 sensor name: camera, scoped name: default::pioneer2dx::camera::link::camera
in world.info().

can you run again?

**Comment by ruizhaogit** [comment]
The critical error is the "Segmentation fault: 11".
The program terminates because of this.
Any idea about the "Segmentation fault"? 
It is from "gazebo.initialize(port=port)".

**Comment by bayesian** [comment]
it is not from gazebo.initialize.. it should be from:         image = self._agent.get_camera_observation("camera")

you can run: python -mpdb  examples/test_simple_navigation.py

**Comment by ruizhaogit** [comment]
I tried again with the "world.info()". It outputs the same thing.

**Comment by ruizhaogit** [comment]
The reason that I think the "segmentation fault: 11" comes form "gazebo.initialize(port=port)" is because when I do this:
"gazebo.initialize(port=port)
 exit()"
The prompt outputs:
"[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.178.20
[Err] [LogRecord.cc:157] LogRecord has not been initialized.
Segmentation fault: 11"

**Comment by ruizhaogit** [comment]
The segmentation fault is the first error.
The "unable to find sensor: camera" is the second error.

**Comment by bayesian** [comment]
you should see some error or warnings when run "gazebo --verbose"? also after you load the world in gazebo, press Ctrl + T, and go to msgs.ImageStamped:  choose /pioneer2dx/camera/link/camera..

**Comment by ruizhaogit** [comment]
"gazebo --verbose" looks ok:
"[Msg] Waiting for master.
Gazebo multi-robot simulator, version 9.8.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.178.20
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.178.20
[Wrn] [GuiIface.cc:122] Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/user_camera/pose, deleting message. This warning is printed only once."

**Comment by ruizhaogit** [comment]
The camera works in my gazebo world:
<img width="452" alt="Screenshot 2019-05-03 at 23 27 42" src="https://user-images.githubusercontent.com/18663623/57166665-2ebf0400-6dfb-11e9-8563-5459b3dc8044.png">

**Comment by ruizhaogit** [comment]
I think the gazebo world is fine.
The problem is the "segmentation fault: 11", which, I think, comes from "pygazebo".

**Comment by bayesian** [comment]
it seems your pygazebo do not build right..

**Comment by ruizhaogit** [comment]
Ok, why it does not build right ...

**Comment by ruizhaogit** [comment]
Build info:
"-- pybind11 v2.3.dev0
-- Found DART: /usr/local/include (Required is at least version "6") found components:  dart
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   thread
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.7.1")
-- Boost version: 1.69.0
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreMain.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreMain.dylib
CMake Warning (dev) at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindBoost.cmake:1031 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindBoost.cmake:1709 (_Boost_MISSING_DEPENDENCIES)
  /usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/share/OGRE/cmake/modules/FindOGRE.cmake:322 (find_package)
  /usr/local/lib/cmake/gazebo/gazebo-config.cmake:175 (find_package)
  CMakeLists.txt:8 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgrePaging.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgrePaging.dylib
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreTerrain.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreTerrain.dylib
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreProperty.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreProperty.dylib
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreRTShaderSystem.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreRTShaderSystem.dylib
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreVolume.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreVolume.dylib
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreOverlay.dylib;debug;/usr/local/Cellar/ogre1.9/1.9-20160714-108ab0bcc69603dba32c0ffd4bbbc39051f421c9_8/lib/libOgreOverlay.dylib
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found suitable version "3.7.1", minimum required is "2.3.0")
-- Checking for module 'uuid'
--   Found uuid, version 1.6.2
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 7.0.1
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
-- Checking for module 'gts'
--   Found gts, version 0.7.6
-- Checking for module 'libswscale'
--   Found libswscale, version 5.3.100
-- Checking for module 'libavdevice >= 56.4.100'
--   Found libavdevice , version 58.5.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.20.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.35.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.22.100
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.8.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.2.2
-- Checking for module 'libzip'
--   Found libzip, version 1.5.2
python include /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/include/python3.7m
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ruizhao/workspace/horizon_social_robot/build"

**Comment by ruizhaogit** [comment]
And build info:
"Scanning dependencies of target pygazebo
[ 50%] Building CXX object pygazebo/CMakeFiles/pygazebo.dir/pygazebo.cc.o
/Users/ruizhao/workspace/horizon_social_robot/pygazebo/pygazebo.cc:237:3: warning: control may reach end of non-void function [-Wreturn-type]
  }
  ^
1 warning generated.
[100%] Linking CXX shared module pygazebo.cpython-37m-darwin.so
[100%] Built target pygazebo"

**Comment by ruizhaogit** [comment]
Is it possible because that I use MacOS X?
In OS X, cmake uses Clang instead of GCC.

**Comment by bayesian** [comment]
we only tried everything working on ubuntu..

**Comment by ruizhaogit** [comment]
Yeah, but it should also work on OS X, since gazebo and python are cross platform.

**Comment by ruizhaogit** [comment]
Thank you for help!

**Comment by emailweixu** [comment]
@ruizhaogit can you run your code with "gdb --args python your test_code.py" and "run" to see the stack trace?

**Comment by ruizhaogit** [comment]
OK, I run the command and get the outputs (didn't see the traceback):
"$ sudo gdb --args python3.7 examples/test_simple_navigation.py
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin18.2.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3.7...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/python3.7 examples/test_simple_navigation.py
[New Thread 0xf03 of process 24637]
During startup program terminated with signal ?, Unknown signal."

But, I manually trace back to "gazebo.initialize(port=port)" in "simple_navigation.py".

**Comment by ruizhaogit** [comment]
I tried to build it on Ubuntu 16.04 and run the python script get following outputs:
"# python3 examples/test_simple_navigation.py
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.31.38.151
X11 connection rejected because of wrong authentication.
[Err] [RenderEngine.cc:728] Can't open display: localhost:10.0
[Wrn] [RenderEngine.cc:93] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:293] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[Err] [LogRecord.cc:157] LogRecord has not been initialized.
[Wrn] [ModelDatabase.cc:340] Getting models from[http://models.gazebosim.org/]. This may take a few seconds.
[Err] [CameraSensor.cc:112] Unable to create CameraSensor. Rendering is disabled.
 joint name: pioneer2dx::pioneer2dx::left_wheel_hinge
 joint name: pioneer2dx::pioneer2dx::right_wheel_hinge
 joint name: pioneer2dx::camera_joint
INFO:social_bot.envs.simple_navigation:joint names: ['pioneer2dx::pioneer2dx::left_wheel_hinge', 'pioneer2dx::pioneer2dx::right_wheel_hinge', 'pioneer2dx::camera_joint']
 joint name: pioneer2dx::pioneer2dx::left_wheel_hinge
 joint name: pioneer2dx::pioneer2dx::right_wheel_hinge
 joint name: pioneer2dx::camera_joint
python3: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::rendering::Camera; typename boost::detail::sp_member_access<T>::type = gazebo::rendering::Camera*]: Assertion `px != 0' failed.
Aborted (core dumped)"

**Comment by ruizhaogit** [comment]
Does this look normal?

**Comment by emailweixu** [comment]
For the last one, I think it's because you don't have a display for the terminal you are running. You need to set environment variable DISPLAY to point to the right X-server. (If you have a local X-Window running, DISPLAY=:0.0 should work)

**Comment by Jialn** [comment]
I've tested on OS X. Also throws an error "Unable to find sensor: camera". Seems there is a problem of supporting OSX.

**Comment by ruizhaogit** [comment]
Hi guys, I want to make a pull request to fix this issue"Unable to find sensor: camera, on MacOS".
Can you grand me the permission to this repository?

"$ git push
remote: Permission to HorizonRobotics/SocialRobot.git denied to ruizhaogit.
fatal: unable to access 'https://github.com/HorizonRobotics/SocialRobot.git/': The requested URL returned error: 403"

**Comment by emailweixu** [comment]
You can first make a fork on github and then push to your github fork and
make a PR.

**Comment by ruizhaogit** [comment]
OK, I made the pull request.

**Comment by ruizhaogit** [comment]
[This pull request](https://github.com/HorizonRobotics/SocialRobot/pull/25) solves this issue.
