### ISSUE TITLE
Tensorflow and tf-agents versions for "Grocery ground pr2" ?

### ISSUE THREAD

**Issue by ruizhaogit** [HorizonRobotics/SocialRobot#24]
Hi @Jialn ,

For the pull request "Grocery ground pr2", which version of tensorfow and tf-agents did you use?

I tried tf-agents (0.2.0rc2) with tensorflow (2.0.0-alpha0), tensorflow (1.13), tf-nightly (1.14) for "Grocery ground pr2".
None of them seems to work...

Thank you!

Best,
Rui

**Comment by Jialn** [comment]
Here is the output by pip freeze on my machine:
...
tf-nightly==1.14.1.dev20190407
tensorboard==1.13.1
tensorflow==2.0.0a0
tensorflow-estimator==1.13.0
tensorflow-tensorboard==1.5.1
-e git+git@github.com:tensorflow/agents.git@21ae8a6b7ccf80b7c693cf34debe68a616c8387e#egg=tf_agents_nightly
-e git+git@github.com:HorizonRobotics/SocialRobot.git@7806d45d4c099fde7755ed3e1fc4d57735bf8db0#egg=social_bot
...
