### ISSUE TITLE
Put some video of the environments in README.md

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/SocialRobot#48]
So that people can get a better idea what are in this project.

**Comment by Jialn** [comment]
OK

**Comment by Jialn** [comment]
It's a little tricky to put video through youtube in mainland these days...  Will gif do ? like this:

![29btl-qu6gv-2](https://user-images.githubusercontent.com/6635652/60653657-085e2900-9e7d-11e9-8b14-99610db44edc.gif)

**Comment by emailweixu** [comment]
Yes
