### ISSUE TITLE
Support render mode "rgb_array"

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/SocialRobot#53]
If this is not too difficult, we should support it so that it will be easier to record video with the newly added recording function in alf (https://github.com/HorizonRobotics/alf/pull/105)

If it's too much trouble to support, we can rely on gzclient to do the recording, though it's not very convenient.

**Comment by Jialn** [comment]
OK， I'll check it.

**Comment by Jialn** [comment]
supported in #61
