### ISSUE TITLE
Env process can not terminate normally

### ISSUE THREAD

**Issue by witwolf** [HorizonRobotics/SocialRobot#88]
1  . run command below, when training finished ,the main process hangs up, `ps aux|grep pr2` info  shows that sub processes for environments are still alive 
```bash
python3 -m alf.bin.train --root_dir=t --gin_file=ppo_pr2.gin \ 
  --gin_param='create_environment.num_parallel_environments=2' \
  --gin_param='TrainerConfig.mini_batch_size=200' \
  --gin_param='TrainerConfig.num_iterations=1'
```

and i found  process terminate timeout   with `self._process.join(5)`

https://github.com/tensorflow/agents/blob/6e7ef806a0f81aa4cf22162f7f708591b0e542a6/tf_agents/environments/parallel_py_environment.py#L289-L290

 just replace the line to `self._process.join()`, you can see it can not go on 

2 . i found it's related to lines below

https://github.com/HorizonRobotics/SocialRobot/blob/88be070bfb15af022cb5c0a4be3953b2a27497c7/pygazebo/pygazebo.cc#L472-L473

but when i remove these lines ,   the sub processes can exit, but  the main process exit with a segment fault  (2 env for collecting data  in sub processes, and  1 env for evaluating in main process )

**Comment by Jialn** [comment]
Fixed now.
